// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTvjiTWoStJTK9TB9vHTKZgVD8DzHm85g',
    appId: '1:100121203970:web:46e4384933f10336e89e1b',
    messagingSenderId: '100121203970',
    projectId: 'safecheckauth',
    authDomain: 'safecheckauth.firebaseapp.com',
    storageBucket: 'safecheckauth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXS8w8KjL2q3EkQCcq6nUiJjKXHrN5LFE',
    appId: '1:100121203970:android:2be98febce5ab3e1e89e1b',
    messagingSenderId: '100121203970',
    projectId: 'safecheckauth',
    storageBucket: 'safecheckauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFClSbvp1GOqrQdndqYH0mYeYmeaGlRY8',
    appId: '1:100121203970:ios:6193c81d05c1e2efe89e1b',
    messagingSenderId: '100121203970',
    projectId: 'safecheckauth',
    storageBucket: 'safecheckauth.firebasestorage.app',
    androidClientId: '100121203970-lvpa5bicph8ajb8g7891f8svevqiqa8c.apps.googleusercontent.com',
    iosClientId: '100121203970-ji38dpjfkn9vuo3qr3ktbuuliphi0gs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFClSbvp1GOqrQdndqYH0mYeYmeaGlRY8',
    appId: '1:100121203970:ios:6193c81d05c1e2efe89e1b',
    messagingSenderId: '100121203970',
    projectId: 'safecheckauth',
    storageBucket: 'safecheckauth.firebasestorage.app',
    androidClientId: '100121203970-lvpa5bicph8ajb8g7891f8svevqiqa8c.apps.googleusercontent.com',
    iosClientId: '100121203970-ji38dpjfkn9vuo3qr3ktbuuliphi0gs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTvjiTWoStJTK9TB9vHTKZgVD8DzHm85g',
    appId: '1:100121203970:web:b838ef7e3f704735e89e1b',
    messagingSenderId: '100121203970',
    projectId: 'safecheckauth',
    authDomain: 'safecheckauth.firebaseapp.com',
    storageBucket: 'safecheckauth.firebasestorage.app',
  );

}